# pinned dependencies to reproduce an entire development environment to use PyNWB with ROS3 support
name: ros3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - h5py==3.6.0
  - hdmf==3.3.2
  - matplotlib==3.5.1
  - numpy==1.21.5
  - pandas==1.3.5
  - python-dateutil==2.8.2
  - setuptools
  - dandi==0.43.0
